// Generated from rockland_heimish_halls_research_jbd_ki_update (1).xlsx on 2026-06-10.
window.simchaMapVenueLeads = [
  {
    "name": "Monsey Palace Halls",
    "category": "Small / Vort / Bar Mitzvah / Shabbos hall",
    "relevance": "Core Heimish",
    "address": "575 Chestnut Ridge Road",
    "cityArea": "Spring Valley, NY 10977",
    "phone": "845-641-5062",
    "email": "",
    "website": "",
    "confidence": "High",
    "reviewPriority": "High",
    "notes": "Listed by The Monsey Kallah as Halls + Vort/Shabbos. TREF describes it as an event venue for weddings, parties, and community gatherings.",
    "verify": "Verify capacity, parking, allowed caterers, pricing, Shabbos availability, music cutoff.",
    "sourceUrls": "https://themonseykallah.com/listing/monsey-palace-halls/ | https://tref.app/listing/monsey-palace-halls.html"
  },
  {
    "name": "Khal Zichron Mordechai",
    "category": "Small / Vort / Bar Mitzvah / Shabbos hall",
    "relevance": "Core Heimish",
    "address": "9 Fosse Ct",
    "cityArea": "Airmont, NY 10952",
    "phone": "845-426-6208",
    "email": "",
    "website": "",
    "confidence": "High",
    "reviewPriority": "Medium",
    "notes": "Listed by The Monsey Kallah as Halls + Vort/Shabbos.",
    "verify": "Verify whether public rentals are accepted; capacity; kitchen; parking; booking contact.",
    "sourceUrls": "https://themonseykallah.com/listing/khal-zichron-mordechai-r-kokis/"
  },
  {
    "name": "Khal Mishkan Yosef Simcha Hall",
    "category": "Small / Vort / Bar Mitzvah / Shabbos hall",
    "relevance": "Core Heimish",
    "address": "13 Algonquin Circle",
    "cityArea": "Airmont, NY 10952",
    "phone": "845-798-9300",
    "email": "",
    "website": "http://www.khalmishkanyosef.org/",
    "confidence": "High",
    "reviewPriority": "High",
    "notes": "Listed by The Monsey Kallah. TREF describes a spacious simcha hall within Khal Mishkan Yosef for celebrations and gatherings.",
    "verify": "Verify current website/contact, capacity, fleishig/milchig kitchen, parking, pricing.",
    "sourceUrls": "https://themonseykallah.com/listing/khal-mishkan-yosef-r-sternberg/ | https://tref.app/listing/simcha-hall/rockland-county-monsey"
  },
  {
    "name": "Toshnad Simcha Hall",
    "category": "Small / Vort / Bar Mitzvah / Shabbos hall",
    "relevance": "Core Heimish",
    "address": "2 Howard Dr",
    "cityArea": "Spring Valley, NY 10977",
    "phone": "845-324-2900; alt 845-425-7759",
    "email": "",
    "website": "",
    "confidence": "High",
    "reviewPriority": "High",
    "notes": "Listed by The Monsey Kallah as Toshnad Heichel Torah Utfila with 845-324-2900. JBD index lists Toshnad Hall; Simcha Center and older directory show alt phone 845-425-7759. Verify current booking line.",
    "verify": "Verify whether 845-324-2900 or 845-425-7759 is the current booking number; confirm capacity, kitchen, parking, pricing.",
    "sourceUrls": "https://themonseykallah.com/listing/toshnad-heichel-torah-utfila/ | https://thejbd.net/eBooks/Upstate/files/basic-html/page24.html | https://thesimchacenter.com/city/monseynew-squaremonroe/listing/toshnad-hall/ | https://online.flipbuilder.com/uqcx/atig/files/basic-html/page34.html"
  },
  {
    "name": "The Crown Ballroom",
    "category": "Small / Vort / Bar Mitzvah / Shabbos hall",
    "relevance": "Core Heimish",
    "address": "70 Highview Rd",
    "cityArea": "Suffern, NY 10901",
    "phone": "718-802-9100",
    "email": "",
    "website": "",
    "confidence": "High",
    "reviewPriority": "Medium",
    "notes": "Listed by The Monsey Kallah as Halls + Vort/Shabbos.",
    "verify": "Verify if phone is correct/current, exact community, capacity, parking, pricing.",
    "sourceUrls": "https://themonseykallah.com/listing/the-crown-ballroom/"
  },
  {
    "name": "Rivnitz Hall",
    "category": "Small / Vort / Bar Mitzvah / Shabbos hall",
    "relevance": "Core Heimish",
    "address": "55 Old Nyack Turnpike",
    "cityArea": "Monsey, NY 10952",
    "phone": "845-426-2056",
    "email": "",
    "website": "",
    "confidence": "High",
    "reviewPriority": "High",
    "notes": "Listed by The Monsey Kallah; Community Connections ad lists Rivnitz/Ribnitz Hall at same address among leading halls.",
    "verify": "Confirm spelling Ribnitz/Rivnitz; capacity; parking; caterer options; pricing.",
    "sourceUrls": "https://themonseykallah.com/listing/cong-ribnitz-hall/ | https://issue.thecommunityconnections.com/3101/271/"
  },
  {
    "name": "Ateres Yechiel Hall of Bobov",
    "category": "Small / Vort / Bar Mitzvah / Shabbos hall",
    "relevance": "Core Heimish",
    "address": "230 Viola Rd",
    "cityArea": "Monsey, NY 10952",
    "phone": "845-356-5001",
    "email": "",
    "website": "",
    "confidence": "High",
    "reviewPriority": "High",
    "notes": "Listed by The Monsey Kallah. TREF describes it as a well-appointed hall in Monsey for simchos/community events under Bobov Yeshiva of Monsey.",
    "verify": "Verify relation to Bobov Monsey Hall at 20 Jill Ln; capacity; parking; pricing.",
    "sourceUrls": "https://themonseykallah.com/listing/ateres-yechiel-hall-of-bobov/ | https://tref.app/listing/simcha-hall/rockland-county-monsey"
  },
  {
    "name": "Borov Hall",
    "category": "Small / Vort / Bar Mitzvah / Shabbos hall",
    "relevance": "Core Heimish",
    "address": "4 Parker Blvd",
    "cityArea": "Monsey, NY 10952",
    "phone": "347-460-7543",
    "email": "",
    "website": "https://www.borov.org/",
    "confidence": "High",
    "reviewPriority": "High",
    "notes": "Listed by The Monsey Kallah. Official Cong. Borov site posts contact # for Simcha Hall as 347-460-7543.",
    "verify": "Verify capacity, separate rooms, kitchen type, pricing, parking, and whether the official 347-460-7543 line is still the only booking line.",
    "sourceUrls": "https://themonseykallah.com/listing/borov-hall-r-moskowitz/ | https://www.borov.org/ | https://thejbd.net/eBooks/Upstate/files/basic-html/page24.html"
  },
  {
    "name": "Khal Beis Elazar - R' Levy",
    "category": "Small / Vort / Bar Mitzvah / Shabbos hall",
    "relevance": "Core Heimish",
    "address": "8 Parker Blvd",
    "cityArea": "Monsey, NY 10952",
    "phone": "845-372-5135",
    "email": "kbezmhall@gmail.com",
    "website": "",
    "confidence": "High",
    "reviewPriority": "High",
    "notes": "Listed by The Monsey Kallah as Halls + Vort/Shabbos.",
    "verify": "Verify email/phone, capacity, fleishig/milchig, pricing, parking.",
    "sourceUrls": "https://themonseykallah.com/listing/beis-elazar-r-levy/"
  },
  {
    "name": "Cong. Shaarei Tefillah - R' Willner",
    "category": "Small / Vort / Bar Mitzvah / Shabbos hall",
    "relevance": "Core Heimish",
    "address": "29 Parker Blvd",
    "cityArea": "Monsey, NY 10952",
    "phone": "845-304-5122",
    "email": "",
    "website": "",
    "confidence": "High",
    "reviewPriority": "Medium",
    "notes": "Listed by The Monsey Kallah as Halls + Vort/Shabbos.",
    "verify": "Verify public booking policy, capacity, pricing, parking.",
    "sourceUrls": "https://themonseykallah.com/listing/cong-shaarei-tefillah-r-willner/"
  },
  {
    "name": "Khal Zichron Michoel - R' Apter",
    "category": "Small / Vort / Bar Mitzvah / Shabbos hall",
    "relevance": "Core Heimish",
    "address": "153 Grandview Ave",
    "cityArea": "Monsey, NY 10952",
    "phone": "917-968-9738",
    "email": "",
    "website": "",
    "confidence": "High",
    "reviewPriority": "Medium",
    "notes": "Listed by The Monsey Kallah as Halls + Vort/Shabbos.",
    "verify": "Verify capacity, kitchen, parking, pricing.",
    "sourceUrls": "https://themonseykallah.com/listing/khal-zichron-michoel-r-apter/"
  },
  {
    "name": "Bais Medrash of Rockland Hall",
    "category": "Small / Vort / Bar Mitzvah / Shabbos hall",
    "relevance": "Core Heimish",
    "address": "2 E Funston Ave",
    "cityArea": "Spring Valley, NY 10977",
    "phone": "845-356-2630",
    "email": "",
    "website": "",
    "confidence": "High",
    "reviewPriority": "Medium",
    "notes": "Listed by The Monsey Kallah as Halls + Vort/Shabbos.",
    "verify": "Verify capacity, booking contact, kitchen, parking.",
    "sourceUrls": "https://themonseykallah.com/listing/bais-medrash-of-rockland/"
  },
  {
    "name": "Cong. Bais Avigdor - R' Chesir",
    "category": "Small / Vort / Bar Mitzvah / Shabbos hall",
    "relevance": "Core Heimish",
    "address": "57 Lime Kiln Rd",
    "cityArea": "Suffern, NY 10901",
    "phone": "773-318-5502",
    "email": "tiferessimchas@gmail.com",
    "website": "https://www.baisavigdorwesleyhills.org/",
    "confidence": "High",
    "reviewPriority": "High",
    "notes": "Listed by The Monsey Kallah as Halls + Vort/Shabbos. Email suggests hall/event contact is Tiferes Simchas.",
    "verify": "Verify if phone is out-of-area but correct; capacity; parking; Shabbos simcha setup.",
    "sourceUrls": "https://themonseykallah.com/listing/cong-bais-avigdor-r-chesir/"
  },
  {
    "name": "Hamaspik Terrace - Monsey Hub",
    "category": "Small / wedding/community hall",
    "relevance": "Core Heimish",
    "address": "58 NY-59 #1",
    "cityArea": "Monsey, NY 10952",
    "phone": "845-425-4949",
    "email": "",
    "website": "",
    "confidence": "High",
    "reviewPriority": "High",
    "notes": "Listed by The Monsey Kallah as Halls + Vort/Shabbos.",
    "verify": "Verify if connected to Valley Terrace booking number; capacity; parking; kitchen/catering.",
    "sourceUrls": "https://themonseykallah.com/listing/hamaspik-terrace/"
  },
  {
    "name": "Garden Paradise - Shoppers Haven",
    "category": "Small / hall",
    "relevance": "Core Heimish",
    "address": "27 Orchard St",
    "cityArea": "Monsey, NY 10952",
    "phone": "845-352-4683",
    "email": "",
    "website": "",
    "confidence": "High",
    "reviewPriority": "Medium",
    "notes": "Listed by The Monsey Kallah as Halls + Vort/Shabbos. Guestay nearby listings call it Garden Paradise Simcha Hall.",
    "verify": "Verify current hall operations, capacity, parking, pricing.",
    "sourceUrls": "https://themonseykallah.com/listing/garden-paradise-shoppers-haven/ | https://guestay.com/newly_renovated_10_bedroom_airmont_mansion/p/519"
  },
  {
    "name": "Bais Yosef Meir Hall - R' Levitan",
    "category": "Small / Vort / Bar Mitzvah / Shabbos hall",
    "relevance": "Core Heimish",
    "address": "19 Olympia Ln",
    "cityArea": "Monsey, NY 10952",
    "phone": "845-396-3776",
    "email": "",
    "website": "",
    "confidence": "High",
    "reviewPriority": "Medium",
    "notes": "Listed by The Monsey Kallah as Halls + Vort/Shabbos.",
    "verify": "Verify booking details, capacity, kitchen, parking.",
    "sourceUrls": "https://themonseykallah.com/listing/bais-yosef-meir-r-levitan/"
  },
  {
    "name": "Cong. Knesses Yisroel - R' Schabes",
    "category": "Small / Vort / Bar Mitzvah / Shabbos hall",
    "relevance": "Core Heimish",
    "address": "698 Union Road",
    "cityArea": "Spring Valley, NY 10977",
    "phone": "845-598-2831",
    "email": "",
    "website": "",
    "confidence": "High",
    "reviewPriority": "Medium",
    "notes": "Listed by The Monsey Kallah as Halls + Vort/Shabbos. Also appears in older local forum recommendations for small halls.",
    "verify": "Verify exact capacity and whether it is suitable for bar mitzvahs/vorts.",
    "sourceUrls": "https://themonseykallah.com/listing/cong-knesses-yisroel-r-schabes/"
  },
  {
    "name": "Cong. Ateres Rosh - R' Rube",
    "category": "Small / Vort / Bar Mitzvah / Shabbos hall",
    "relevance": "Core Heimish",
    "address": "16 Charlotte Drive",
    "cityArea": "Spring Valley, NY 10977",
    "phone": "845-239-9130",
    "email": "",
    "website": "",
    "confidence": "High",
    "reviewPriority": "Medium",
    "notes": "Listed by The Monsey Kallah as Halls + Vort/Shabbos.",
    "verify": "Verify booking, capacity, parking, pricing.",
    "sourceUrls": "https://themonseykallah.com/listing/cong-ateres-rosh-r-rube/"
  },
  {
    "name": "KYWH; R' Senter's hall",
    "category": "Small / Vort / Bar Mitzvah / Shabbos hall",
    "relevance": "Core Heimish",
    "address": "1 Harriet Lane",
    "cityArea": "Spring Valley, NY 10977",
    "phone": "",
    "email": "simchahall@kywh.org",
    "website": "",
    "confidence": "High",
    "reviewPriority": "High",
    "notes": "Listed by The Monsey Kallah as Halls + Vort/Shabbos. Email provided but no phone found in listing.",
    "verify": "Find phone; verify capacity, kitchen, parking, prices.",
    "sourceUrls": "https://themonseykallah.com/listing/kehillat-yeshorim-of-wesley-hills-r-senter/"
  },
  {
    "name": "Cong. Ahavas Yitzchok - R' Rudinsky",
    "category": "Small / Vort / Bar Mitzvah / Shabbos hall",
    "relevance": "Core Heimish",
    "address": "73 Forshay Road",
    "cityArea": "Monsey, NY 10952",
    "phone": "845-320-2590",
    "email": "",
    "website": "https://www.ahavasyitzchok.org/",
    "confidence": "High",
    "reviewPriority": "Medium",
    "notes": "Listed by The Monsey Kallah as Halls + Vort/Shabbos.",
    "verify": "Verify hall rental contact, capacity, kitchen, pricing.",
    "sourceUrls": "https://themonseykallah.com/listing/congregation-ahavas-yitzchok-rudinsky/"
  },
  {
    "name": "Cong. Shaar Hashamayim - R' Veiner",
    "category": "Small / Vort / Bar Mitzvah / Shabbos hall",
    "relevance": "Core Heimish",
    "address": "71 E Willow Tree Road",
    "cityArea": "Spring Valley, NY 10977",
    "phone": "845-216-9572",
    "email": "ghhorowitz@gmail.com",
    "website": "",
    "confidence": "High",
    "reviewPriority": "High",
    "notes": "Listed by The Monsey Kallah as Halls + Vort/Shabbos.",
    "verify": "Verify email/phone, capacity, parking, pricing.",
    "sourceUrls": "https://themonseykallah.com/listing/r-veiners-shul/"
  },
  {
    "name": "Ateres Charna",
    "category": "Wedding",
    "relevance": "Core Heimish",
    "address": "790 N Main St",
    "cityArea": "Spring Valley, NY 10977",
    "phone": "845-362-7800",
    "email": "",
    "website": "",
    "confidence": "High",
    "reviewPriority": "High",
    "notes": "Listed by The Monsey Kallah as a wedding hall. JBD wedding hall page lists Ateres Charna at 790 N Main St. SV with 845-362-7800. The Event Address also lists it as a Monsey-area wedding ballroom.",
    "verify": "Verify capacity, pricing packages, L'Chaim Catering relationship/exclusivity, parking, simcha types, and current booking email.",
    "sourceUrls": "https://themonseykallah.com/listing/ateres-charna/ | https://thejbd.net/eBooks/Upstate/files/basic-html/page668.html | https://theeventaddress.com/venue/ | https://online.flipbuilder.com/uqcx/atig/files/basic-html/page24.html"
  },
  {
    "name": "Atrium Ballroom",
    "category": "Wedding",
    "relevance": "Core Heimish",
    "address": "401 NY-59",
    "cityArea": "Monsey, NY 10952",
    "phone": "845-356-0000; JBD alt 845-356-9136/7",
    "email": "",
    "website": "",
    "confidence": "High",
    "reviewPriority": "High",
    "notes": "Listed by The Monsey Kallah and The Event Address as The Atrium/The Atrium Ballroom at 401 NY-59. JBD wedding page lists The Atrium Plaza at 401 W. Rt. 59 with alt phone 845-356-9136/7. Verify which number is current.",
    "verify": "Verify current booking number between 845-356-0000 and 845-356-9136/7; capacity, packages, parking, caterer rules, smaller rooms.",
    "sourceUrls": "https://themonseykallah.com/listing/atrium-ballroom/ | https://theeventaddress.com/venue/ | https://thejbd.net/eBooks/Upstate/files/basic-html/page668.html | https://online.flipbuilder.com/uqcx/atig/files/basic-html/page24.html"
  },
  {
    "name": "Valley Terrace (YSV)",
    "category": "Wedding",
    "relevance": "Core Heimish",
    "address": "121 College Rd",
    "cityArea": "Monsey/Suffern area, NY 10952/10901",
    "phone": "845-425-4949; JBD alt 845-352-4683 x5; directory alt 845-742-6321",
    "email": "",
    "website": "",
    "confidence": "High",
    "reviewPriority": "High",
    "notes": "Listed by The Monsey Kallah and The Event Address. JBD wedding page lists Valley Terrace (Yeshiva S.V.) at 121 College Rd with 845-352-4683 x5; older useful phone list shows 845-742-6321. Treat as phone conflict until verified.",
    "verify": "Confirm city/ZIP displayed for address; current booking line; capacity, pricing, parking, mechitzah setup, and package options.",
    "sourceUrls": "https://themonseykallah.com/listing/valley-terrace-ysv/ | https://theeventaddress.com/venue/ | https://thejbd.net/eBooks/Upstate/files/basic-html/page668.html | https://online.flipbuilder.com/uqcx/atig/files/basic-html/page24.html"
  },
  {
    "name": "Vilchovitz Hall",
    "category": "Wedding",
    "relevance": "Core Heimish",
    "address": "230 Maple Ave",
    "cityArea": "Kaser / Monsey, NY 10952",
    "phone": "845-731-3707; Viznitz alt 845-731-3735",
    "email": "",
    "website": "",
    "confidence": "High",
    "reviewPriority": "High",
    "notes": "Listed by The Monsey Kallah and The Event Address. JBD wedding page lists Vilchovitz (Viznitz) at 230 Maple Ave with 845-731-3707; older useful phone list also shows Viznitz Hall alt 845-731-3735.",
    "verify": "Confirm spelling Vilchovitz/Vilchocitz; current booking number; exact capacity, parking, pricing, relation to Tiferes Elka/Viznitz.",
    "sourceUrls": "https://themonseykallah.com/listing/vilchovitz-hall/ | https://theeventaddress.com/venue/ | https://thejbd.net/eBooks/Upstate/files/basic-html/page668.html | https://online.flipbuilder.com/uqcx/atig/files/basic-html/page24.html"
  },
  {
    "name": "Tiferes Elka",
    "category": "Wedding",
    "relevance": "Core Heimish",
    "address": "2 School Terrace",
    "cityArea": "Monsey, NY 10952",
    "phone": "845-731-3707",
    "email": "",
    "website": "",
    "confidence": "Medium-High",
    "reviewPriority": "High",
    "notes": "The Event Address lists Tiferes Elka at 2 School Terrace, phone 845-731-3707. JBD wedding page also lists Tiferes Elka at 2 School Ter with 845-731-3707. Rockland Daily article previously noted large hall/parking information.",
    "verify": "Confirm official booking number, address entrance, current capacity/parking, packages, and whether hall rental-only is available.",
    "sourceUrls": "https://theeventaddress.com/venue/ | https://thejbd.net/eBooks/Upstate/files/basic-html/page668.html | https://www.rocklanddaily.com/"
  },
  {
    "name": "Ateres Chaya Surah Hall",
    "category": "Wedding",
    "relevance": "Core Heimish",
    "address": "106 S Madison Ave",
    "cityArea": "Spring Valley, NY 10977",
    "phone": "845-519-1212",
    "email": "",
    "website": "",
    "confidence": "Medium-High",
    "reviewPriority": "High",
    "notes": "TREF and The Event Address list Ateres Chaya Surah as a Spring Valley wedding venue. JBD wedding page confirms 106 S Madison Av. SV and 845-519-1212.",
    "verify": "Verify current management, capacity, pricing, parking, caterer restrictions, and whether booking@kihalls.com applies here too.",
    "sourceUrls": "https://tref.app/listing/ateres-chaya-surah-hall.html | https://theeventaddress.com/venue/ | https://thejbd.net/eBooks/Upstate/files/basic-html/page668.html | https://online.flipbuilder.com/uqcx/atig/files/basic-html/page24.html"
  },
  {
    "name": "Ateres Genendel",
    "category": "Wedding",
    "relevance": "Core Heimish",
    "address": "80 S Madison Ave",
    "cityArea": "Spring Valley, NY 10977",
    "phone": "845-519-1212",
    "email": "booking@kihalls.com",
    "website": "",
    "confidence": "Medium",
    "reviewPriority": "High",
    "notes": "Listed by The Event Address as Ateres Genendel at 80 S Madison Ave, same phone as Ateres Chaya Surah. User-provided PDF is for Keser Inzlicht at 80 South Madison Ave with the same 845-519-1212 phone and KI Halls booking email added by user. Verify if Keser Inzlicht, Ateres Genendel, and/or KI Halls are same building/management or separate halls.",
    "verify": "Verify official hall name(s), whether Keser Inzlicht is a separate hall from Ateres Genendel, current package, parking, and if booking@kihalls.com is used for all KI halls.",
    "sourceUrls": "https://theeventaddress.com/venue/ | Uploaded file: Contract_780(1).pdf | User supplied: booking@kihalls.com"
  },
  {
    "name": "Alfei Menashe Ballroom",
    "category": "Small / Vort / Bar Mitzvah / Shabbos hall",
    "relevance": "Core Heimish",
    "address": "244 Viola Road",
    "cityArea": "Monsey, NY 10952",
    "phone": "845-474-2425",
    "email": "",
    "website": "",
    "confidence": "High",
    "reviewPriority": "High",
    "notes": "Monsey Scoop reported it opened March 2025 at Imrei Binah Yeshiva for sheva brachos, bar mitzvahs, vorts, tenoyim and more; TREF lists same phone/address.",
    "verify": "Verify capacity, booking contact, packages, parking, if exclusive caterer still current.",
    "sourceUrls": "https://monseyscoop.com/new-alfei-menashe-ballroom-opens-at-imrei-binah-yeshiva-on-viola-road-for-simchas/ | https://tref.app/listing/simcha-hall/rockland-county-monsey"
  },
  {
    "name": "Tertzal Simcha Hall",
    "category": "Small / Vort / Bar Mitzvah / Shabbos hall",
    "relevance": "Core Heimish",
    "address": "15 Cedar Ln",
    "cityArea": "Monsey, NY 10952",
    "phone": "845-425-8222",
    "email": "",
    "website": "",
    "confidence": "Medium-High",
    "reviewPriority": "High",
    "notes": "TREF lists Tertzal Simcha Hall and notes all-in-one package with event coordination; Wheree notes location and says parking is not dedicated/street parking can be challenging.",
    "verify": "Verify capacity, exact package details, food/catering, parking situation, pricing.",
    "sourceUrls": "https://tref.app/listing/simcha-hall/rockland-county-monsey | https://tertzal-simcha-hall.wheree.com/"
  },
  {
    "name": "The Schlesinger Hall",
    "category": "Small / Vort / Bar Mitzvah / Shabbos hall",
    "relevance": "Core Heimish",
    "address": "33 Union Road",
    "cityArea": "Spring Valley, NY 10977",
    "phone": "845-302-9077",
    "email": "",
    "website": "",
    "confidence": "Medium-High",
    "reviewPriority": "High",
    "notes": "TREF lists The Schlesinger Hall as an event venue at 33 Union Road. Community Connections ad lists Schlesinger Hall among leading halls served by Mashmanim.",
    "verify": "Verify capacity, contact, parking, food/catering options, pricing.",
    "sourceUrls": "https://tref.app/listing/simcha-hall/rockland-county-monsey | https://issue.thecommunityconnections.com/3101/271/"
  },
  {
    "name": "Birchos Yosef Nikolsburg",
    "category": "Small / Vort / Bar Mitzvah / Shabbos hall",
    "relevance": "Core Heimish",
    "address": "6 Milton Pl",
    "cityArea": "Spring Valley, NY 10977",
    "phone": "845-478-4101",
    "email": "",
    "website": "",
    "confidence": "Medium-High",
    "reviewPriority": "High",
    "notes": "Official Nikolsburg contact page lists Simcha Hall of Nikolsburg at 6 Milton Place, Spring Valley, NY 10977, Tel 845-478-4101. JBD index also lists Nikolsburg Hall.",
    "verify": "Verify capacity, open-to-public policy, caterer rules, pricing, and parking.",
    "sourceUrls": "https://www.nikolsburg.org/contact | https://thejbd.net/eBooks/Upstate/files/basic-html/page24.html | https://online.flipbuilder.com/uqcx/atig/files/basic-html/page34.html"
  },
  {
    "name": "Tiferes Gedalia Hall",
    "category": "Small / Vort / Bar Mitzvah / Shabbos hall",
    "relevance": "Core Heimish",
    "address": "9 Saddle River Rd",
    "cityArea": "Monsey/Rockland, NY 10952",
    "phone": "845-587-5531",
    "email": "",
    "website": "",
    "confidence": "Medium-High",
    "reviewPriority": "Medium",
    "notes": "TREF describes it as an intimate venue within Tiferes Gedalia Shul for small simchas/community events; Community Connections ad lists Tiferes Gedalya Hall 9 Saddle River Rd.",
    "verify": "Verify exact capacity, address/city, parking, pricing.",
    "sourceUrls": "https://tref.app/listing/simcha-hall/rockland-county-monsey | https://issue.thecommunityconnections.com/3101/271/"
  },
  {
    "name": "Kozlov Hall",
    "category": "Small / Vort / Bar Mitzvah / Shabbos hall",
    "relevance": "Core Heimish",
    "address": "40 Paikin Drive",
    "cityArea": "Spring Valley, NY 10977",
    "phone": "845-222-6244",
    "email": "",
    "website": "",
    "confidence": "Medium",
    "reviewPriority": "High",
    "notes": "TREF lists Congregation Bais Simcha at 40 Paikin Drive. Community Connections ad lists Kozlov Hall at 40 Paikin Dr; likely related/duplicate but not confirmed.",
    "verify": "Confirm if Bais Simcha and Kozlov Hall are the same listing; official hall name; capacity; parking; pricing.",
    "sourceUrls": "https://tref.app/listing/simcha-hall/rockland-county-monsey | https://issue.thecommunityconnections.com/3101/271/ | https://tref.app/listing/kozlov-hall.html"
  },
  {
    "name": "Grand View Simcha Hall",
    "category": "Small / Vort / Bar Mitzvah / Shabbos hall",
    "relevance": "Core Heimish",
    "address": "250 Kiryas Radin Drive",
    "cityArea": "Spring Valley, NY 10977",
    "phone": "848-216-5212",
    "email": "",
    "website": "",
    "confidence": "Medium-High",
    "reviewPriority": "Medium",
    "notes": "TREF page 2 lists Grand View Simcha Hall at 250 Kiryas Radin Drive.",
    "verify": "Verify capacity, public rentals, parking, pricing.",
    "sourceUrls": "https://tref.app/listing/simcha-hall/rockland-county-monsey/p%3A2"
  },
  {
    "name": "Simcha Hall (Bobov)",
    "category": "Small / Vort / Bar Mitzvah / Shabbos hall",
    "relevance": "Core Heimish",
    "address": "20 Jill Ln",
    "cityArea": "Monsey, NY 10952",
    "phone": "845-420-0334",
    "email": "",
    "website": "",
    "confidence": "Medium-High",
    "reviewPriority": "High",
    "notes": "TREF lists Simcha Hall (Bobov) at 20 Jill Ln; Community Connections ad lists Bobov Monsey Hall 20 Jill Ln.",
    "verify": "Verify relation to Ateres Yechiel Hall of Bobov on Viola; capacity; parking; pricing.",
    "sourceUrls": "https://tref.app/listing/simcha-hall/rockland-county-monsey/p%3A2 | https://issue.thecommunityconnections.com/3101/271/"
  },
  {
    "name": "Beth Medrash D'Monsey Simcha Hall",
    "category": "Small / Vort / Bar Mitzvah / Shabbos hall",
    "relevance": "Core Heimish",
    "address": "3 Harvest Ct",
    "cityArea": "Monsey, NY 10952",
    "phone": "845-587-9140",
    "email": "",
    "website": "",
    "confidence": "Medium-High",
    "reviewPriority": "High",
    "notes": "Community Connections ad lists Beth Medrash D'Monsey at 3 Harvest Ct. Chamber of Commerce search result says phone is 845-587-9140. Guestay nearby listings also show this hall.",
    "verify": "Verify phone, booking contact, capacity, kitchen, parking.",
    "sourceUrls": "https://issue.thecommunityconnections.com/3101/271/ | https://www.chamberofcommerce.com/business-directory/new-york/monsey/banquet-hall/2002281872-beth-medrash-d-monsey-simcha-hall | https://guestay.com/2_bedroom_family_getaway_in_monsey_wesley_hills/p/504"
  },
  {
    "name": "Forshay Hall",
    "category": "Small / Vort / Bar Mitzvah / Shabbos hall",
    "relevance": "Core Heimish",
    "address": "49 Forshay Rd",
    "cityArea": "Monsey, NY 10952",
    "phone": "845-641-0491; alt 347-633-6561; directory alt 845-304-9796",
    "email": "",
    "website": "",
    "confidence": "Medium",
    "reviewPriority": "High",
    "notes": "Listed by The Monsey Kallah. JBD index lists Forshay Hall. A Kol Hatzibur PDF snippet advertises Forshay Hall at 49 Forshay Monsey, 50 couples, wheelchair accessible, ample parking, booking 347-633-6561. Older directory lists 845-304-9796. Verify current booking number.",
    "verify": "Confirm current booking line; capacity, wheelchair access, parking, kitchen, pricing.",
    "sourceUrls": "https://themonseykallah.com/listing/forshay-hall/ | https://thejbd.net/eBooks/Upstate/files/basic-html/page24.html | https://07322371170284514432.googlegroups.com/attach/18e199df50490/3677.pdf?part=0.1 | https://online.flipbuilder.com/uqcx/atig/files/basic-html/page34.html"
  },
  {
    "name": "Ohel Yaakov Hall",
    "category": "Small / Vort / Bar Mitzvah / Shabbos hall",
    "relevance": "Core Heimish",
    "address": "1 Challenger Ct",
    "cityArea": "Rockland/Monsey area",
    "phone": "845-356-1057 (older directory; verify)",
    "email": "",
    "website": "",
    "confidence": "Medium-Low",
    "reviewPriority": "High",
    "notes": "JBD index lists Ohel Yaakov Hall. Existing research had no phone. Older directory useful numbers list Ohel Yaakov Hall at 845-356-1057; verify because this may be outdated.",
    "verify": "Verify whether 845-356-1057 is current; confirm address, capacity, kitchen, parking, rental policy.",
    "sourceUrls": "https://thejbd.net/eBooks/Upstate/files/basic-html/page24.html | https://online.flipbuilder.com/uqcx/atig/files/basic-html/page34.html"
  },
  {
    "name": "Karlin Stolin Hall",
    "category": "Small / Vort / Bar Mitzvah / Shabbos hall",
    "relevance": "Core Heimish",
    "address": "52 Main St",
    "cityArea": "Monsey, NY 10952",
    "phone": "845-519-7005",
    "email": "",
    "website": "",
    "confidence": "Medium-Low",
    "reviewPriority": "High",
    "notes": "JBD index lists Karlin-Stolin Hall. Simcha Center and older directory useful numbers list Karlin Stolin Hall at 845-519-7005.",
    "verify": "Verify address, current booking phone, public rental policy, capacity, kitchen, parking.",
    "sourceUrls": "https://thejbd.net/eBooks/Upstate/files/basic-html/page24.html | https://thesimchacenter.com/city/monseynew-squaremonroe/listing/karlin-stolin-hall/ | https://online.flipbuilder.com/uqcx/atig/files/basic-html/page34.html"
  },
  {
    "name": "Premishlan Hall",
    "category": "Small / Vort / Bar Mitzvah / Shabbos hall",
    "relevance": "Core Heimish",
    "address": "38 Herrick Ave",
    "cityArea": "Spring Valley/Monsey area",
    "phone": "",
    "email": "",
    "website": "",
    "confidence": "Medium-Low",
    "reviewPriority": "Medium",
    "notes": "Community Connections ad lists Premishlan Hall 38 Herrick Ave among leading halls served by Mashmanim.",
    "verify": "Find phone, exact city/ZIP, verify active rental, capacity, parking.",
    "sourceUrls": "https://issue.thecommunityconnections.com/3101/271/"
  },
  {
    "name": "Crowne Plaza Suffern",
    "category": "Hotel / kosher-capable venue",
    "relevance": "Adjacent / not strictly Heimish",
    "address": "3 Executive Blvd",
    "cityArea": "Suffern, NY 10901",
    "phone": "845-357-4800",
    "email": "",
    "website": "",
    "confidence": "Medium",
    "reviewPriority": "Low",
    "notes": "Chosson & Kallah lists Holiday Inn Suffern as having an exclusively kosher kitchen with catering by L'Chaim Catering. This is likely not a Heimish hall but useful as an adjacent Rockland venue.",
    "verify": "Verify kosher kitchen status, L'Chaim relationship, suitability for Heimish simchas, capacity/pricing.",
    "sourceUrls": "https://www.chossonandkallah.com/new-york/jewish-wedding/Halls.html"
  },
  {
    "name": "Keser Inzlicht",
    "category": "Small / Sheva Brachos / Bar Mitzvah / Pidyon Haben hall",
    "relevance": "Core Heimish",
    "address": "80 South Madison Ave",
    "cityArea": "Spring Valley, NY 10977",
    "phone": "845-519-1212",
    "email": "booking@kihalls.com",
    "website": "",
    "confidence": "High",
    "reviewPriority": "High",
    "notes": "Uploaded contract/package: standard package $2,600 includes meal for 25 couples; smaller hall option with 20 couples for $1,999. Event types on form: Sheva Bruchos, Bar Mitzva, Pidyen Haben. Policies include no outside food/drinks/cakes/miniatures, no party planners, no live music, hall 7PM-11:15PM, menu pre-selected, 3 simchas per night, $750 deposit, balance due 2 weeks before simcha, 3% CC fee.",
    "verify": "Verify official hall name, whether Keser Inzlicht is same/related to Ateres Genendel/KI Halls, current pricing, parking, allowed music, exact capacity, and package availability.",
    "sourceUrls": "Uploaded file: Contract_780(1).pdf | User supplied: booking@kihalls.com"
  },
  {
    "name": "Pupa Hall / Tzoin Yosef Hall",
    "category": "Wedding / affordable hall / small simcha lead",
    "relevance": "Core Heimish",
    "address": "15 Widman Ct",
    "cityArea": "Monsey / Spring Valley, NY",
    "phone": "845-371-1220 x6; older directory 845-371-1220",
    "email": "",
    "website": "",
    "confidence": "Medium-High",
    "reviewPriority": "High",
    "notes": "JBD wedding halls page lists Pupa Hall (Affordable), 15 Widman Ct, 845-371-1220 x6. JBD index also lists Pupa Hall under Halls. Older community/directory snippets refer to Pupa Hall/Tzoin Yosef.",
    "verify": "Verify exact official name, current booking extension, open-to-public policy, allowed caterers, capacity, parking, packages.",
    "sourceUrls": "https://thejbd.net/eBooks/Upstate/files/basic-html/page668.html | https://thejbd.net/eBooks/Upstate/files/basic-html/page24.html | https://online.flipbuilder.com/uqcx/atig/files/basic-html/page34.html"
  },
  {
    "name": "Ateres Freida",
    "category": "Wedding hall",
    "relevance": "Core Heimish",
    "address": "103 Clinton Ln",
    "cityArea": "New Square / Spring Valley, NY 10977",
    "phone": "845-364-9244",
    "email": "",
    "website": "",
    "confidence": "Medium-High",
    "reviewPriority": "High",
    "notes": "JBD wedding halls page lists Ateres Freida at 103 Clinton Ln. SV with phone 845-364-9244.",
    "verify": "Confirm hall is available to broader public; capacity, parking, pricing packages, caterer rules, exact address/entrance.",
    "sourceUrls": "https://thejbd.net/eBooks/Upstate/files/basic-html/page668.html"
  },
  {
    "name": "Avir Yakov",
    "category": "Wedding hall",
    "relevance": "Core Heimish",
    "address": "15 Roosevelt Ave",
    "cityArea": "New Square / Spring Valley, NY 10977",
    "phone": "845-354-6728",
    "email": "",
    "website": "",
    "confidence": "Medium-High",
    "reviewPriority": "High",
    "notes": "JBD wedding halls page lists Avir Yakov at 15 Roosevelt Ave with phone 845-354-6728.",
    "verify": "Confirm official hall name/spelling, availability to public, capacity, parking, pricing packages, caterer rules.",
    "sourceUrls": "https://thejbd.net/eBooks/Upstate/files/basic-html/page668.html"
  },
  {
    "name": "Bluefield Catering / Hall Lead",
    "category": "Catering / hall lead from JBD halls index",
    "relevance": "Core Heimish lead",
    "address": "",
    "cityArea": "Monsey / Spring Valley area",
    "phone": "845-328-0978",
    "email": "bluefieldmonsey@gmail.com",
    "website": "",
    "confidence": "Medium-Low",
    "reviewPriority": "High",
    "notes": "JBD halls index lists Bluefield Catering under Halls. Monsey Luach ad snippets identify Bluefield Catering contact as Aharon Ganzfried, 845-328-0978, bluefieldmonsey@gmail.com. Needs verification whether this is a hall rental, catering-only, or a caterer tied to halls.",
    "verify": "Call to verify if they operate or book a hall, what venues they serve, pricing, package style, hashgacha, and whether listing belongs under catering instead of halls.",
    "sourceUrls": "https://thejbd.net/eBooks/Upstate/files/basic-html/page24.html | https://monseyluach.com/wp-content/uploads/2025/09/Issue-18.pdf"
  },
  {
    "name": "Hava Java Hall / Catering Lead",
    "category": "Dairy / cafe / catering hall lead",
    "relevance": "Heimish-friendly lead",
    "address": "59 NY-59; also 455 NY-306",
    "cityArea": "Monsey, NY 10952",
    "phone": "Town Square 845-371-5282; Wesley 845-362-1019",
    "email": "",
    "website": "https://havajavaonline.com/",
    "confidence": "Medium-Low",
    "reviewPriority": "Medium",
    "notes": "JBD halls index lists Hava Java Hall. Hava Java official site lists Town Square at 59 NY-59 and Wesley at 455 NY-306 with the two phone numbers shown. Verify whether Hava Java Hall is a private event room/catering option or just a restaurant/cafe listing.",
    "verify": "Verify exact event-room location, capacity, dairy/private-event rules, hashgacha, catering manager, and whether they want a listing under halls or food.",
    "sourceUrls": "https://thejbd.net/eBooks/Upstate/files/basic-html/page24.html | https://havajavaonline.com/"
  },
  {
    "name": "Monsey Catering / Monsey Take-Out Lead",
    "category": "Catering / possible hall lead",
    "relevance": "Core Heimish lead",
    "address": "46 Main Street",
    "cityArea": "Monsey, NY 10952",
    "phone": "845-425-2300",
    "email": "monseytakeout@gmail.com",
    "website": "https://monseytakeout.com/",
    "confidence": "Low-Medium",
    "reviewPriority": "Medium",
    "notes": "JBD halls index lists Monsey Catering. Monsey Take-Out official site lists Monsey Kosher Take-Out at 46 Main Street with 845-425-2300 and monseytakeout@gmail.com. Treat as possible match until verified.",
    "verify": "Verify if 'Monsey Catering' is same as Monsey Take-Out or a separate hall/caterer; determine correct category for SimchaMap.",
    "sourceUrls": "https://thejbd.net/eBooks/Upstate/files/basic-html/page24.html | https://monseytakeout.com/"
  },
  {
    "name": "Glaubers Catering / Glauber's Kosher Bakery Lead",
    "category": "Catering / hall lead from JBD halls index",
    "relevance": "Core Heimish lead",
    "address": "126 Maple Ave",
    "cityArea": "Spring Valley, NY 10977",
    "phone": "845-352-4683",
    "email": "",
    "website": "",
    "confidence": "Low-Medium",
    "reviewPriority": "Medium",
    "notes": "JBD halls index lists Glaubers Catering under Halls. Older directory lists Glauber's Kosher Bakery at 845-352-4683. Verify whether this is a caterer, bakery, hall, or tied to another venue.",
    "verify": "Call to confirm if there is an actual hall or if it belongs under bakery/catering; verify address, current phone, packages.",
    "sourceUrls": "https://thejbd.net/eBooks/Upstate/files/basic-html/page24.html | https://online.flipbuilder.com/uqcx/atig/files/basic-html/page34.html"
  },
  {
    "name": "Nitra Monsey Hall",
    "category": "Hall lead from older directory",
    "relevance": "Core Heimish lead",
    "address": "",
    "cityArea": "Monsey / Spring Valley area",
    "phone": "914-806-5163",
    "email": "",
    "website": "",
    "confidence": "Low",
    "reviewPriority": "Medium",
    "notes": "Older directory useful numbers list Nitra Monsey Hall with 914-806-5163. Not found in JBD halls index in this pass; added as a manual review lead, not confirmed.",
    "verify": "Verify if hall is still active, official name, address, current phone, capacity, parking, and public rental policy.",
    "sourceUrls": "https://online.flipbuilder.com/uqcx/atig/files/basic-html/page34.html"
  },
  {
    "name": "Vengrov Hall",
    "category": "Hall lead from older directory",
    "relevance": "Core Heimish lead",
    "address": "",
    "cityArea": "Monsey / Spring Valley area",
    "phone": "845-426-5745",
    "email": "",
    "website": "",
    "confidence": "Low",
    "reviewPriority": "Medium",
    "notes": "Older directory useful numbers list Vengrov Hall with 845-426-5745. Not cross-confirmed in this pass; added as manual review lead.",
    "verify": "Verify official spelling, address, current phone, whether still active, capacity, parking, and rental policy.",
    "sourceUrls": "https://online.flipbuilder.com/uqcx/atig/files/basic-html/page34.html"
  },
  {
    "name": "Gourmet Affair Halls",
    "category": "Hall/catering lead from older directory",
    "relevance": "Heimish-friendly lead",
    "address": "",
    "cityArea": "Monsey / Spring Valley area",
    "phone": "845-304-0532",
    "email": "",
    "website": "",
    "confidence": "Low",
    "reviewPriority": "Medium",
    "notes": "Older directory useful numbers lists Gourmet Affair under Halls with 845-304-0532. Not cross-confirmed in this pass; added as manual review lead.",
    "verify": "Verify if this is a hall, caterer, or event service; current phone; address; capacity; package options.",
    "sourceUrls": "https://online.flipbuilder.com/uqcx/atig/files/basic-html/page34.html"
  }
];
